### PR TITLE
Set upstream X-Forwarded Host and For headers if not present

### LINKED ISSUE #847: Setting upstream host breaks Istio
The forwarding proxy sets the upstream request host by coping it from the incoming request breaking Envoy upstream when the upstream protocol is set to HTTP. 

## Expected Behaviour

The gateway function calls should work inside Istio mesh.

## Current Behaviour
The gateway function calls fail with 404 since Envoy forwards the request back to the Gateway due to the host setting. 

## Possible Solution

Remove the host forward from: https://github.com/openfaas/faas/blob/master/gateway/handlers/forwarding_proxy.go#L79

## Steps to Reproduce (for bugs)

1. Install OpenFaaS on a Istio enabled cluster
2. Rename the function service port to `http`
3. Call a function from the Gateway UI or CLI
4. Trace the call with Jaeger

## Context

Trying to get OpenFaaS running inside Istio mesh.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
GKE 1.10 and Istio 1.0.1
* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

### PR DESCRIPTION
**Pull request by stefanprodan**
## Description

This PR does the following:
*  Fix #847 by removing the http client host override
* X-Forwarded-For and X-Forwarded-Host are usually handled by the ingress controller, if those headers are not set then the gateway will create them

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Tested using `stefanprodan/of-env:1.0.0`locally and on GKE with Istio ingress gateway.

Http_X_Forwarded_For was `127.0.0.1:44238` and after the patch it shows the real IP of the caller.

Http_X_Forwarded_Host is set by the gateway when no reverse proxy sets it first.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: gateway/handlers/forwarding_proxy.go [hunk 1]
```diff
@@ -100,6 +103,8 @@ func forwardRequest(w http.ResponseWriter, r *http.Request, proxyClient *http.Cl
 	ctx, cancel := context.WithTimeout(context.Background(), timeout)
 	defer cancel()
 
+	log.Printf("Upstream request to: %s, %+v\n", upstreamReq.URL.Path, upstreamReq)
```
Comment (alexellis) [inline gateway/handlers/forwarding_proxy.go]: Is this log statement new? I don't see it on the left side of the diff

**Comment by alexellis** [comment]
Derek set milestone: 0.9.2
