### PR TITLE
Change how and when we fetch and parse namespace info

### LINKED ISSUE #1408: Namespace selector does not update the function list
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

If I  deploy functions to the default namespace and to an additional namespace, the namespace selector in the gateway UI does not appear to work.  The API returns the expected result with a new function list, but he UI does not update to reflect this

In this screenshot you can see the latest API response but with the wrong function list rendered
image

## Expected Behaviour

The function list should change to show the functions from the selected namespace

## Current Behaviour

Found while walking through a demo of multinamespace support

## Steps to Reproduce (for bugs)

1. Deploy on kubernetes with the latest helm chart `openfaas-5.3.8`, make sure to set `clusterRole` to true
2. Create an annotate an extra namespace
    ```sh
    kubectl create ns dev-fn
    kubectl annotate ns dev-fn openfaas="true"
   ```
2. use the cli to deploy left pad to an extra namespace, `faas-cli store deploy Left-Pad -n dev-fn`
3. also deploy a function to the default namespace `faas-cli store deploy NodeInfo`
3. Open the gateway ui
5. use the namespace selector to change to `dev-fn`
6. observer that the function list does not change, it should still just show `NodeInfo`

## Context

Relates to #1379

## Your Environment

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
faas-netes

* Operating System and version (e.g. Linux, Windows, MacOS):
osx

### PR DESCRIPTION
**Pull request by Waterdrips**
## Description

The initial namespace select implementation had some challenges, especially around non-default installs (no openfaas-fn namespace)
This has removed lots of those issues and added some more user friendly bits too (defaulting to first returned namespace from backend, passing that namespace to the function-create as default)

Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [x] My issue has received approval from the maintainers or lead with the `design/approved` label
closes #1408 
closes #1408 

## How Has This Been Tested?

kubernetes:
Install with 4 active namespaces, switching works, adding a fn works (for each namespace)
Can add the same fn to each namespace
Can call each fn, see it calls correct one in logs
Can delete functions

Swarm:
No NS selector, can create, call and delete fns.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: gateway/assets/script/bootstrap.js [hunk 1]
```diff
@@ -603,4 +600,8 @@ function uuidv4() {
     return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, function(c) {
         return (c ^ cryptoInstance.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
     })
-}  
\ No newline at end of file
+}
+
+function getNamespaceSuffix(namespace) {
```
Comment (LucasRoesler) [inline gateway/assets/script/bootstrap.js]: this is a small complaint, but it looks like this returns a query parameter, not a suffix.  It also requires this method to be called first because it returns the `?`, this will make it a little fragile is someone doesn't recognize that the order is important. Javascript has a URL object https://developer.mozilla.org/en-US/docs/Web/API/URL that might be easier to use and more robust to work with, since the search params object has a set method https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/set

Comment (Waterdrips) [reply gateway/assets/script/bootstrap.js]: @LucasRoesler 
The URL object doesn't support relative paths, and the CORS blocking on localhost means that using `new URL(document.lcoation.domain)` to generate a url `localhost:8080` and then using the url object to do this stuff doesnt work because (at least) chrome block the requests (when i tried anyway) a rename and re-structure of this is incoming. Hopefully its better.

Comment (LucasRoesler) [reply gateway/assets/script/bootstrap.js]: wow that is an incredibly disappointing API in JS then :(

Comment (Waterdrips) [reply gateway/assets/script/bootstrap.js]: I mean it worked, but because mostly people will be using localhost CORS gets in the way and makes things hard

**Comment by alexellis** [comment]
Merging based upon review from @LucasRoesler
