### PR TITLE
Fix fnc image name in the ui

### LINKED ISSUE #990: UI: Refresh image tag on periodic basis
## Expected Behaviour

The image tag should change when deploying a new version in the UI.

## Current Behaviour

The state has changed in the cluster but is cached on the UI for efficiency and shows the older tag version. This was confusing for one of our users "zeeque" who reported this on Slack.

## Possible Solution

We just need to bust the cache or refresh the objects when we refresh the list of functions.

## Steps to Reproduce (for bugs)

1. Deploy a function
2. Update the tag
3. Deploy it again

screenshot 2018-12-04 at 09 58 09

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description

- Update the function image value during the `refreshData`
- Apply vscode default JS/TS formatting

### Note 
Please start your review with the commit 3fe8267 this contains the actual implementation change
The second commit is purely formatting changes.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Resolves #990 

## How Has This Been Tested?

This manually tested in a local deployment
0. update docker-compose to mount the local assets folder,  adding this to the `gateway` definition
```yaml
        volumes:
            - "./gateway/assets:/home/app/assets"
```
1. deploy to docker swarm using the `./deploy_stack.sh`
2. deploy a project using `faas-cli up -f stack.yml --tag=sha`
3. open the function details in the ui
4. modify the function, commit, and redeploy using `faas-cli up -f stack.yml --tag=sha`
5. observe that the Image field updates to match the new git sha

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: gateway/assets/script/bootstrap.js [hunk 1]
```diff
@@ -180,29 +180,32 @@ app.controller("home", ['$scope', '$log', '$http', '$location', '$interval', '$f
...
-                            // update the selected function object because the newly fetched object from the API becomes a different object
-                            var filteredSelectedFunction = $filter('filter')($scope.functions, {name: $scope.selectedFunction.name}, true);
-                            if (filteredSelectedFunction && filteredSelectedFunction.length > 0) {
-                                $scope.selectedFunction = filteredSelectedFunction[0];
-                            } else {
-                                $scope.selectedFunction = undefined;
-                            }
+            var cl = function (previousItems) {
+                $http.get("../system/functions").then(function (response) {
+                    if (response == null || response.data == null) {
```
Comment (kenfdev) [inline gateway/assets/script/bootstrap.js]: I don't think we should change this because this may not catch when the `response` or `response.data` is `undefined`. Also, we should always use triple equals `===` whenever possible (which some existing code doesn't include).

Comment (LucasRoesler) [reply gateway/assets/script/bootstrap.js]: I am familiar with the `===` rule in JS, but explicitly chose `==` because it does catch `undefined`.

**Comment by LucasRoesler** [comment]
@kenfdev sorry for the confusion on the review, I should have linked to the logical change directly.  i explicitly split the PR into two commits so that we can separate the logical change from the formatting change

File: gateway/assets/script/bootstrap.js (hunk 1 above)
Comment (kenfdev) [reply gateway/assets/script/bootstrap.js]: Thanks for clearing it out! I wasn't sure how loose it was. 

```
response && response.data
```

The previous statement is probably an anti-pattern in JS if we think strictly, as it catches falsy values (like 0, "").
(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else#Description)

IMHO, I think the previous code was more readable, but am not against this change either.

Comment (LucasRoesler) [reply gateway/assets/script/bootstrap.js]: I am ok with rewriting it, but my reason for writing it this way it reduces the nesting / indentation level and keeps the primary logic close to the primary level of the. I generally prefer to check for errors/issues and return early and allow the expected or happy path to be the primary logic of a method

Comment (kenfdev) [reply gateway/assets/script/bootstrap.js]: Oh, sorry Lucas, I was missing the whole point. Somehow I only thought the code was changed from no `null` statement to using `null` in the if statement. So I thought the change after that was due to formatting. Sorry about me not understanding the intent.

> I generally prefer to check for errors/issues and return early

This cleared what I thought was strange and I agree about returning early.

**Comment by alexellis** [comment]
Can we do a PR which changes the formatting and nothing else then overlay this PR?

**Comment by alexellis** [comment]
Can we do a PR which changes the formatting and nothing else then overlay this PR?

**Comment by LucasRoesler** [comment]
I already broke it into two commits, if you want I can simply remove the second commit, which is only the formatting changes

**Comment by alexellis** [comment]
Thanks for doing that, but unfortunately it doesn't make it any easier for reviewing on GitHub. Could you do a PR from the first commit?

**Comment by LucasRoesler** [comment]
sure, i figured the two commits could be reviewed individually, but I will roll it back so that only the first is in this PR

File: gateway/assets/script/bootstrap.js (hunk 1 above)
Comment (ivanayov) [reply gateway/assets/script/bootstrap.js]: You can do a check with `(!response && !response.data)` as well.

Comment (alexellis) [reply gateway/assets/script/bootstrap.js]: I prefer the original code for this which like Ken says is more readable. Also unless I'm reading this wrong, we reversed the logic. Can you help me understand the change?

```
// do something if there is a value for response.data
if (response && response.data) {
```

Changed to:

```
// do something if and only if either are null?

if (response == null || response.data == null) {
```

Comment (LucasRoesler) [reply gateway/assets/script/bootstrap.js]: if there is no response or there is no data, then stop processing the response and return immediately.  Ideally, this would actually throw and error or set an error state in the UI, but that is beyond the scope of this PR

I did this so that

1) the primary intention of the function (update the function data) is the main scope of the function, error and edge cases are checked and dealt with prior to the success case; and
2) it reduces the number of indented blocks and the indentation level as a whole, i find long nested chunks of code hard to read
